# NOTE: update this with your service name
service: prisma2-f1-demo

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packagerOptions:
      scripts: # this is the magic
        - prisma generate

  serverless-offline:
    port: 4000

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  vpc:
    securityGroupIds:
      - sg-06d91384d018ecc06
    subnetIds:
      - subnet-07510a4f906a2d08e
      - subnet-003df4b8ca8c73b77
      - subnet-0a6f3e2a57aa0fec1
      - subnet-0fd08d630da24e4c8
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}

functions:
  graphql:
    handler: src/graphql.graphqlHandler
    environment:
      SLS_DEBUG: true
    events:
      - http:
          path: graphql
          method: post
          cors: true
          integration: lambda-proxy

      - http:
          path: graphql
          method: get
          cors: true
          integration: lambda-proxy
